project 'TranslationApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TranslationApp' do


  pod 'AFNetworking'

  pod 'Masonry'

    pod 'IQKeyboardManager'
    pod 'LCText'

end
